Modify  1-install_nginx_web_server

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,34 +1,33 @@
 #!/usr/bin/env bash
-#install and configure nginx on
+#install ngix and have a file that returns the string "Hello World  inside
 
-apt-get -y update && apt-get install -y nginx
-if [ $? -eq 0 ] 
+sudo apt-get update -y && \
+sudo apt-get install -y nginx
+if [ $? -eq 0 ]
 then
-	#create directory and file to be served
-	mkdir -p /var/www/school/html
-	chown -R $USER:$USER /var/www/school/html
-	chown -R 755 /var/www
-	echo "Hello World!!" > /var/www/school/html/index.html
-
-	#configure nginx
-	cp /etc/nginx/sites-available/default /etc/nginx/sites-available/school
-	echo -e "server {
-	listen 80;
-	listen [::]:80;
-	root /var/www/school/html;
-	index index.html;
-	location / {
-		try_files $url $url/ =404;
-	}
-	
-}" > /etc/nginx/sites-available/school
-ln -s /etc/nginx/sites-available/school /etc/nginx/sites-enabled/
-
-systemctl restart nginx
-if [ $? -ne 0 ]
-then 
-	echo "Could not start nginx"
-fi
+    echo -e \
+"http {
+    root /var/www/school;
+    index index.html;
+    server {
+        listen 80;
+        location \ {
+        }
+    }
+}
+events {
+}" > /etc/nginx/nginx.conf
+    mkdir -p /var/www/school
+    echo "Hello World!" > \
+	/var/www/school/index.html
+    service nginx start
+    if [ $? -ne 0 ]
+    then
+	"Problem starting nginx"
+	exit 1
+    fi
 else
-	echo "Could not install nginx."
+    echo "Could not install nginx"
+    exit 1
 fi
+exit 0
